# version: '3'
# services:
#   web:
#     build: .
#     command: gunicorn yourapp.wsgi:application --bind 0.0.0.0:8000
#     volumes:
#       - .:/app

version: "2"
services:
  web:
    container_name: easyschool
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    ports:
      - "8000:8000"