apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-school-deployment
  labels:
    app: easy-school
spec:
  replicas: 3
  selector:
    matchLabels:
      app: easy-school
  template:
    metadata:
      labels:
        app: easy-school
    spec:
      containers:
      - name: easy-school
        image: octe/easyschool:latest
        ports:
        - containerPort: 8080
      #   volumeMounts:
      #   - name: config-volume
      #     mountPath: /config
      # volumes:
      # - name: config-volume
      #   configMap:
      #     name: easy-school-config
